task: detection
num_classes: 9
remap_mscoco_category: False
train_dataloader_source:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:/confmix_data/real_yolo/kitti/source/images
    ann_file: C:/confmix_data/coco_json/kitti_train_3000.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 4
  drop_last: True
train_dataloader_target:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:/confmix_data/real_yolo/cityscapes/train/images
    ann_file: C:/confmix_data/coco_json/cityscapes_train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 4
  drop_last: True
val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: C:/confmix_data/real_yolo/cityscapes/val/images
    ann_file: C:/confmix_data/coco_json/cityscapes_val.json
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  batch_size: 1
  num_workers: 4
  drop_last: False