__include__: [
  '../dataset/sim10k2city_custom.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer_city.yml',
  './include/r50_p2_i1.yml',
]
output_dir: ./output/rtdetrx_sim10k2city
PResNet:
  depth: 101
  variant: d
  freeze_at: 0
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: True
HybridEncoder:
  hidden_dim: 384
  dim_feedforward: 2048
  eval_spatial_size: [736, 736]
RTDETRTransformer:
  feat_channels: [384, 384, 384]
  hidden_dim: 384
  eval_spatial_size: [736, 736]
RTDETR:
  num_classes: 9
  multi_scale: ~
SetCriterion:
  num_classes: 9
RTDETRPostProcessor:
  num_classes: 9
